"use strict";
exports.__esModule = true;
var MobileLibrary_1 = require("./MobileLibrary");
var mobile2_1 = require("../reto repaso 3/mobile2");
var movil1 = new mobile2_1.Mobile();
movil1.setName("Xiaomi Mi11");
movil1.setCameraNumber(5);
movil1.setColor("negro");
movil1.setIs5G(true);
movil1.setSdSize(128);
movil1.setPrice(700);
var movil2 = new mobile2_1.Mobile();
movil2.setName("Samsung Galaxy s21");
movil2.setCameraNumber(3);
movil2.setColor("azul");
movil2.setIs5G(true);
movil2.setSdSize(128);
movil2.setPrice(750);
var movil3 = new mobile2_1.Mobile();
movil3.setName("OnePlus 9 Pro");
movil3.setCameraNumber(4);
movil3.setColor("gris");
movil3.setIs5G(true);
movil3.setSdSize(256);
movil3.setPrice(909);
var movil4 = new mobile2_1.Mobile();
movil4.setName("iPhone X");
movil4.setCameraNumber(3);
movil4.setColor("negro");
movil4.setIs5G(true);
movil4.setSdSize(64);
movil4.setPrice(348);
var mobiles;
mobiles = [movil1, movil2, movil3, movil4];
var Libreria = new MobileLibrary_1.MobileLibrary("Almacen1", "Madrid", mobiles);
Libreria.totalPriceCalculator();
console.log(Libreria);
console.log(Libreria.totalPriceCalculator());
Libreria.setLocation("Getafe");
console.log(Libreria.getLocation());
console.log(Libreria.getMobiles());
Libreria.getMobiles()[0].print();
Libreria.setTotalPrice(30002);
console.log(Libreria.getTotalPrice());
